#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pangrams' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

#MY ANSWER STARTS HERE

def pangrams(s):
    ans=[0]*26
    slist = list(s)
    for i in slist:
        if i != " ":  #THIS IS TO ELIMINATE SPACES. THE TEST STANDARD HACKERHANK TEST CASES DID NOT CATCH THIS ERROR
            ans[((ord(i) % 65) % 32)]+=1
    if 0 in ans:
        return ("not pangram")
    else:
        return ("pangram")

#FINISHES HERE

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = pangrams(s)

    fptr.write(result + '\n')

    fptr.close()

"""PROBLEM DESCRIPTION

A pangram is a string that contains every letter of the alphabet. 
Given a sentence determine whether it is a pangram in the English alphabet. 
Ignore case. Return either pangram or not pangram as appropriate."""
