#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

# Here is the answer

def plusMinus(arr):
    ans=[0, 0, 0]
    for i in arr:
        if i>0:
            ans[0]+=1
        elif i<0:
            ans[1]+=1
        else:
            ans[2]+=1
    for i in range(3):
        ans[i]/=len(arr)
        print(f'{ans[i]:.6f}')

# Answer ended here

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
