#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

# Here is the answer

def plusMinus(arr):
    ans=[0, 0, 0]
    for i in arr:
        if i>0:
            ans[0]+=1
        elif i<0:
            ans[1]+=1
        else:
            ans[2]+=1
    for i in range(3):
        ans[i]/=len(arr)
        print(f'{ans[i]:.6f}')

# Answer ended here

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)

"""PROBLEM DESCRIPTION STARTS HERE

Given an array of integers, calculate the ratios of its elements that are positive, negative, and zero. 
Print the decimal value of each fraction on a new line with  places after the decimal.

Example:
arr=[1,1,0,-1,-1]

there are n=5 elements, two positive, two negative and one zero.
Their ratios are 2/5=0.400000, 2/5=0.400000 and 1/5=0.200000.
Results are printed as:
0.400000
0.400000
0.200000

Constraints:
0<n<=100
-100<=arr[i]<=100"""
