#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

# MY ANSWER STARTS HERE

def timeConversion(s):
    if s[8:]=="PM":
        s = str(int(s[:2]) % 12 +12)+s[2:8]
        return (s)
    elif int(s[:2]) % 12 <10:
        s = "0" + str(int(s[:2]) % 12)+s[2:8]
        return (s)
    else:
        s = str(int(s[:2]) % 12)+s[2:8]
        return (s)

#MY ANSWER FINISHES HERE

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()

"""Problem Description

Given a time in 12-hour AM/PM format, convert it to military (24-hour) time.

Note: - 12:00:00AM on a 12-hour clock is 00:00:00 on a 24-hour clock.
- 12:00:00PM on a 12-hour clock is 12:00:00 on a 24-hour clock.

Example
*s='12:01:00PM'
Return '12:01:00'.

*s='12:01:00AM'
Return '00:01:00'."""
